### ISSUE TITLE
make bot publish stop on outdated and unused-dependencies

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#22]
bot publish runs the analyze tasks, reporting outdated and unused-dependencies.
I wish bot publish would stop if any issues are found in these categories, and there was a flag to publish in spite of those issues. so by default the publish would only succeed on no issues.

**Comment by goloroden** [comment]
Thanks for reporting this issue, we'll have a look at it, and get back to you.

Please give us a little time for this.

**Comment by goloroden** [comment]
Okay, let's split this issue into three separate tasks:

### Stop publishing when `analyze` fails

This is already the default behavior. You can not publish anything if it fails code analysis and / or tests. So there is no need to change anything here.

### Stop publishing when `outdated` fails

This does not make sense, IMHO. It does not break anything, and it does not do any harm. It's just that you do not use the latest versions. Hence it is a warning. This will stay this way, especially because it happens from time to time that you can not yet update. Hence it is useful to get this warning every time, but you should be able to publish nonetheless. It's not a show stopper (other than a failed code analysis).

### Stop publishing when `unused-dependencies` fails

On this, you are right: Publishing should stop here, because it just does not make sense to publish a module with a non-needed sub-module. It only increases install time unnecessarily. In case there is a false positive there is the option to exclude specific modules from the check (this check already existed in the past), so that's easy to fix here. The default behavior is now changed, so when any unused dependencies are found, publishing stops.

**Comment by stefanheine** [comment]
> Stop publishing when unused-dependencies fails
>
> [...]
> In case there is a false positive there is the option to exclude specific modules from the check (this check already existed in the past), so that's easy to fix here. The default behavior is now changed, so when any unused dependencies are found, publishing stops.

how do I exclude a module? we have a module mentioned in package.json, delivering a team-specific eslint-config, so that is never referenced in source files. the `exclude` option in `task('universal/unused-dependencies', {` does not help here.

**Comment by goloroden** [comment]
This is currently a bug that I'm working on.
Right now, the only solution is to stick to an old version of roboter.

Sorry for that :-(
