### ISSUE TITLE
Multiple analyze scopes.

### ISSUE THREAD

**Issue by grundhoeferj** [thenativeweb/roboter#42]
If you are building a wolkenkit application with `server` and `client` in the same project it is currently not possible to lint `server` and `client` with different sets of rules.

It would be great if you could apply multiple sets of rules, each with a different `src` and `rules` option.

**Comment by goloroden** [comment]
It actually *is* possible: You need to add separate `roboter.js` files to the two different directories.

I don't think that we will change this behavior due to the following reasons:

- It does not only affect code analysis, but also testing, publishing, … this means a lot of work.
- It only affects a few number of projects, because most projects that use roboter use one repository per project.

Combined this means lots of work for a few number of projects, hence I think that we will rather not do this.

Is there a special reason why two `roboter.js` files don't work for your case?

**Comment by goloroden** [comment]
We are currently rewriting roboter from scratch, so this shouldn't be an issue any more once the new version has been published.
