### ISSUE TITLE
roboter does not support React 16

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/roboter#50]
Hi Golo,

roboter does not support React 16 (in bot watch-app) as it's using totally outdated versions of webpack-dev-server and the related packages.

I know you're working on a rewrite... and are not motivated to work on roboter. still this is an issue for us, since we'd like to use roboter for this in spite of configuring webpack on our own in all projects.

I can't do a pull request, since the roboter build process is magic for me... I can't simply fork and test, since the roboter-client (that needs the main updates) is somehow generated and automatically published on npm.

I have a working webpack configuration for React 16 running here.

please let me know if you're willing to spend some time on roboter for these updates (or if there is an ETA for the new roboter with the needed functionality).
or if you can provide assistance for me to understand how roboter can be build and tested by me, so I could fix the code and create a PR.

Regards
  Stefan

**Comment by goloroden** [comment]
Hi @stefanheine 😊 

To answer the simple ones:

- No, we won't invest any more time into the legacy code (of course, this is not nice, but I think it's understandable).
- And no, unfortunately, there is no ETA available.

What I really value is that you offer to send a PR, but I wonder if it wouldn't make way more sense if you could help to build the new one, instead of fixing the old one? What do you think?

**Comment by stefanheine** [comment]
let me know what state the new one is in, and how helping to build could look like.
I'm definitely willing to test if you have something that's in a somewhat usable state.

**Comment by goloroden** [comment]
I will get back to you soon 😊

**Comment by mattwagl** [comment]
Hi @stefanheine! Thanks for reaching out to us. Would be great to get some help in pushing roboter to the next level. I'll try to give you as much background as possible. The new version is code named [`vnext`](https://github.com/thenativeweb/roboter/tree/vnext).

What are our design goals for the next version:

- As little configuration as possible. To us roboter is a tool to manifest our development philosophy in code. So custom configuration has always been a double sided sword for us. So for the next version we want to try to ged rid of as much custom configuration as possible. That's why we've started out `vnext` without the `roboter.js` that the current version uses to configure tasks. One example for this is the new `analyse` task. It comes with `eslint-config-es` by default. You can override this configuration by simply creating a `.eslintrc.json` in your project. But we won't include more options than that. Another example is the new `test` task. It now simple checks for the existence of a `test` folder inside your project and treasts each subfolder as a test type. So in order to create unit tests you simply create a subfolder `units` and put your tests into that. No need to configure anything else. Just like in the old version `pre` and `post` test lifecycle tasks work like before.
- As little dependencies as possible. A lot of the things we've been struggling in the past were keeping things up to date and to align roboter with our core dependency gulp. If possible we want to loose dependency weight in favor of smaller dependencies that do one job well.
- Integrate all the learnings from wolkenkit cli to make the new CLI more managable and to make contributions easier.
- Simplify testing in order to make contributions easier.
- Embrace async/await.
- Small core. Custom tasks (maybe as separate packages)

So what's the current state?

- Development has been started in the `vnext` branch
- So far we've implemented the following tasks…
  - license
  - test
  - analyse
- While creating these tasks we've layed out the foundation and the framework for handling parameters etc.
- We've also created a simpler way to test each task. For each task you create a new test folder that contains test cases. Each case is again just a folder. Our test framework then runs the rober CLI with the task name against this folder e.g. analyses the files with eslin. It then checks the result and output of the roboter CLI against the `expected.js` file. The task author can use this file to define the desired exit code and output of the current test case. Simply clone the branch, install the dependencies and run `npm run test`.

The following things are still in flux and haven't been decided…

- How do we deal with different working contexts (client vs. server)? Is this still needed? My current gut feeling is: no. Because you might also want to bundle backend code with webpack e.g. to make it compatible with older node versions. For different bundling scenarios (SPA, server, univeral-module) we could create additional modules that just provide webpack configurations.
- How do we name the new task for packing/bundling? How do we name the development mode? Or is it just `bot bundle -w` for the watch mode?

We would love to get you on board with this. You could be the CTO (chief task officer) 😁 of the new `bundle` task and we could maybe work this out together? If you want to get a feel for how this could work you can have a look at the source code of the [analyse](https://github.com/thenativeweb/roboter/blob/vnext/lib/cli/commands/analyse.js) task and its [test cases](https://github.com/thenativeweb/roboter/tree/vnext/test/integration/analyse).

**Comment by mattwagl** [comment]
I've created a simple [Proof of Concept in a new vnext branch](https://github.com/thenativeweb/roboter/tree/vnext-bundle) for the bundle task. It currently only uses webpack and babel. There no additionals loaders like postcss yet. From there on we can decide on how to move on… 

My initial goal was to create a [skeleton for the command itself](https://github.com/thenativeweb/roboter/blob/vnext-bundle/lib/cli/commands/bundle.js) as well as [two simple tests](https://github.com/thenativeweb/roboter/tree/vnext-bundle/test/integration/bundle) that validate if it works…

**Comment by stefanheine** [comment]
Hi @mattwagl ,

thanks for providing this update.

> As little configuration as possible. To us roboter is a tool to manifest our development philosophy in code.

that raises the danger of others not being able to use the tool.
eslint config is fine. we already have our own set of rules referenced in .eslintrc.json.
two configs we have in most of the roboter.js configs:
- increasing the limit of the mocha timeouts for the live tests. of course that can be configured per test, but with large number of tests that all take long due to a slow backend (that we can't control), it's simpler to have a central configuration
- docker jobs for 'build/publish/remove/run'. so we simply run 'bot docker' and all this is handled automatically bringing the new version into production. of course we could build a own script and handle as 'npm run docker'.

> license

I hope you still handle it like in today's roboter: if no license is configured in package.json, you skip the license check.

> How do we deal with different working contexts (client vs. server)? Is this still needed? My current gut feeling is: no.

we use both, but maybe that can be done much simpler:
client: no bundling or translation needed. the app is simply called as 'node app.js' via docker.
server: babel/webpack/bundling is needed, but happens in the docker creation (the Dockerfile contains a 'npm run build' call, that triggers the build process - so we're not committing built code into git). plus the webpack-dev-server job used during development work.


I just wanted to play with your new version a little and tried installing it into my app as:
`  "roboter": "https://github.com/thenativeweb/roboter.git#vnext",`
but that already failed during npm install.

Regards
  Stefan

**Comment by mattwagl** [comment]
@stefanheine 

>  that raises the danger of others not being able to use the tool.

Yes, you're right! But we have to find a sensible balance here in order to make development of roboter sustainable to us. But that's why I'm happy we're talking to you in order to find out how to get to the right balance :-)

# Special needs: testing

So you need a way to set special options for your tests. Especially long-running ones. Maybe the [mocha.opts](https://mochajs.org/#mochaopts) would be an interesting way. This would follow the path of the eslint configuration. We should check if this works.

# Special needs: custom shell tasks

You need a way to define custom shell tasks. I think we should definetely keep this option but we still have to define a place where to specify them. Maybe the package.json scripts block is an interesting place to do so. Or do you think definining them in JavaScript is important to you?

# license

Concerning the `license` task: It skips the license check if no license is found. See this [check in the vnext-branch](https://github.com/thenativeweb/roboter/blob/98b130d6d5e37cf55203c80b194b1950d9153dc9/lib/cli/commands/license.js#L196).

# Different contexts: client vs. server

Ok, it seems to mew like you don't need the contexts and the bundle task at all as you bundle all things by yourself.

# Failing install

Can you share the error log? What errors did you get?

**Comment by goloroden** [comment]
As said, we won't fix this for the current roboter versions.

The upcoming version, which has been rewritten from scratch, will solve this. It won't take that long any more 😊 

Hence I am going to close this issue.
