### ISSUE TITLE
remove dependency on babel

### ISSUE THREAD

**Issue by stheine** [thenativeweb/roboter#67]
> Optional: Precompile code using Babel

for this, you include babel

```
  "dependencies": {
    "babel-cli": "6.26.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.1",
```

but due to the versions in there, it prevents me from upgrading my project to @babel/core@7 with @babel/preset-env@7. (well, I can upgrade, but it will fail due to the mix of babel@6 and babel@7).

can you find a way to remove that hard dependency, and maybe switch to a peer dependency only? that would allow me to upgrade my project and continue, since I'm not using roboter's babel functionality anyhow.

**Comment by mattwagl** [comment]
Hey @stheine long time no see! :-) Thanks for reaching out.

I don't think we will drop the hard dependency. `peer-dependencies` still feels weird in usage and we don't want to install all the babel dependencies into all our modules that currently use it. So I think upgrading to babel7 seems like the way to go.

Since we also stumpled upon a version conflict recently, we thought a test branch would be a good option – so we've create the [upgrade-to-babel-7](https://github.com/thenativeweb/roboter/tree/upgrade-to-babel-7) branch, upgraded to babel7 and made the test work. So it seems like this could work. But before merging this to master, we'd like to verify this works with some of our babel-heavy projects. This might take some time.

You could help us by installing and testing this branch. Would be interesting to see if this works for you.

**Comment by goloroden** [comment]
@stheine Ping ;-)

**Comment by stheine** [comment]
thanks. I can confirm that the fix works.
