### ISSUE TITLE
Skipping license check – a good idea?

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/roboter#672]
### What is this question about?

I was wondering whether it's actually a good idea to skip the license check if no license configuration file was found. Of course, on the one hand, that's the way it worked before 12.0.0, and you also get a hint in the output.

On the other hand, so far we *had* a license check, if a license was given in the `package.json` file. This is not the case any more. Instead, it (more or less silently) gets skipped. And even if you define a license configuration file – you just have to have a typo in the file name, and it will be skipped. That could be critical.

What if we said that you always have to have a license configuration file, which, in doubt, allows you to disable the license check? This way you would be on the much more safe side.

(Another scenario I fear is: Creating a new project, someone forgets to copy over the license configuration file ("we'll do that later…"), and boom, you have introduced a legal problem.

@yeldiRium What do you think?

**Comment by yeldiRium** [comment]
After we had a discussion about this a week ago, I need to order my thoughts on this.

The first points of criticism for the current implementation are:

- Skipping the license check (due to the new way the configuration works) might give a false sense of security if it goes unnoticed
- The warning that the license check is being skipped is not obvious enough

And the result of this issue and the discussion were the two options to either:

- treat a missing licenseCheck.json configuration file as an error and fail the license check. this could be paired with an opt-out that could be configured in said configuration file
- make the skip-warning so obvious that is cannot be missed

---

I don't think it is possible to make the warning more noticable without resorting to multi-line ascii art. I am also not a fan of forcing the existence of a configuration file to get rid of a feature, since it clutters the project root.

However, this cluttering of the project root is becoming the norm and most configuration files are easily recognizable as such, since they usually start with a `.`, which I failed to think about when implementing the new way the license check is configured. I think if we were to rename our config file to `.licenseCheck.json` (or, to avoid a major version bump, if we would allow it with and without the dot in front), the cluttering argument would be less relevant.

I still don't like forcing the existence of the file, but I also agree that a license check is important enough to warrant the cautiousness.

So my current stance is: Allow the configuration file to be named `.licenseCheck.json`, require a configuration file to exist, allow license-check-opt-out in the configuration file.

**Comment by goloroden** [comment]
@yeldiRium Thanks for writing this summary. With a little bit of distance to our discussion I don't worry that much any more about skipping it, I could live with that 😉

With respect to making the skip message more prominent: I've noticed that I don't get colorized output, so if it was a warning (in yellow, as in roboter <12) I think it would be more prominent already.

**Comment by yeldiRium** [comment]
That is very weird, since it uses `buntstift.warn` for the skip-warning, which in the used version of `buntstift` uses `chalk.yellow.bold`... But I can reproduce the issue. It is not colored for me aswell.

Then I'll look into why this is, fix it, and we're done here ;)

**Comment by goloroden** [comment]
IIRC we can force buntstift to provide color, and not auto-detect it … could this maybe help?

**Comment by yeldiRium** [comment]
Yes, that's what I'm currently researching as well. We would need to provide a way to override the color-level in buntstift to force the use of color. However, that would only fix our own output.

But since we already agreed in #671 to rewrite the eslint/npm-package-json-lint output ourselves, this is not an issue.
