### ISSUE TITLE
Why does `test -w` not run the tests at start?

### ISSUE THREAD

**Issue by Michel73** [thenativeweb/roboter#69]
When I execute `npx roboter test -w`, I don't see that any tests being executed. Only after saving. It would be nice if first the are executed and then watching the files.
Version: 1.0.7

**Comment by mattwagl** [comment]
@Michel73 the reason was lazyness I guess. :-) But it seems you're lucky: I had a small free time slot today and was able to create a branch (https://github.com/thenativeweb/roboter/tree/execute-tests-on-start) and played around with the idea. You could help us by installing this branch and testing the watch mode with your project.

@goloroden What do you think?

**Comment by goloroden** [comment]
@Michel73 First of all, thanks for bringing up this issue 😊! You're right that this is unexpected, and that it would make sense to have this behavior!

@mattwagl Thanks for taking care of this immediately! I like your solution, so basically we could have a PR here 🎉 

As you, @mattwagl, already suggested it would be great if you, @Michel73, could test the changes, and let us know if it works for you 😊

**Comment by mattwagl** [comment]
Awesome! When I find some time, I‘ll create a PR and then let‘s wait for some feedback from @Michel73.

One last question: we could apply the same behaviour to the „analyse“ task as well. I would include that in this branch.

**Comment by mattwagl** [comment]
@Michel73 Has been released as `1.1.0` on npm. Have fun!

**Comment by Michel73** [comment]
Works fine for me, thanks.
