### ISSUE TITLE
CC-BY/Artistic licenses and Compatibility

### ISSUE THREAD

**Issue by hyandell** [thenativeweb/roboter#860]
Hi Native Web folk,

I love the idea of the project. I'm a big believer that users should not be surprised when using a project to discover a dependency has a surprising license. My background is with Apache's licensing committee and OSPOs (currently a member of the AWS OSPO), so worrying about user surprise is common for me.

I wanted to question both Artistic and CC-BY being considered compatible for the permissive licenses in https://github.com/thenativeweb/roboter/blob/main/licenseCheck.json - I noticed this when seeing a roboter.js file that was considering the spdx of "MIT AND CC-BY-3.0" to be compatible with MIT. 

Both of those licenses have concepts that go beyond the classic permissive licenses and may be considered a surprise. As an easy example, the Apache Software Foundation does not consider them to be akin to Apache-2.0 ( https://www.apache.org/legal/resolved.html ).

There are a lot more SPDX codes that I believe you can consider permissive-compatible; Apache's site above lists some and I can list more if you'd be interested.

**Comment by goloroden** [comment]
@hyandell Thanks for bringing up this issue.

The file you mentioned is not meant as an exhaustive list of compatible licenses, it's just the list of licenses we consider to be compatible for `roboter` itself.

Since we (apparently) don't have dependencies with Artistic and / or CC-BY-* licenses, these aren't listed there, as it is just not needed. As said, this is the minimal list of licenses to ensure that we are fine from a legal POV with `roboter`.

If you want to use `roboter` in one of your projects, you have to come up with a compatibility list yourself. This is due to two reasons:

1. We don't know which license you are going to use, so we don't want to take care of managing lists for every possible license.
2. We don't give legal advice, we only provide the tool to verify license integrity. It's up to you as a user of `roboter` to figure out which licenses can be considered compatible, e.g. with your lawyer.

Hence, to cut a long story short, thanks for the offer, but for the moment it works as expected. So I'm going to close this issue.

**Comment by hyandell** [comment]
Thank you Golo; apologies for misunderstanding the use case.

I'll follow up with the project I saw including a roboter.js file with a default compatibility list to give them feedback on their defaults.

I wasn't sure what you meant by "don't have dependencies with Artistic and / or CC-BY-* licenses, these aren't listed there", as I see them listed on your licenseCheck.json - https://github.com/thenativeweb/roboter/blob/main/licenseCheck.json

**Comment by goloroden** [comment]
You're right – I actually missed these ones when writing my answer. Sorry for that.
