### ISSUE TITLE
Cannot handle comments in json files

### ISSUE THREAD

**Issue by rooboo** [thenativeweb/roboter#971]
The generated tsconfig.json consists of numerous comments when created by tsc --init. The roboter cannot handle those comments an throws the following error:
```
tsconfig.json: Unexpected token / in JSON at position 31
    at parse (<anonymous>)
    at ESMLoader.jsonStrategy (node:internal/modules/esm/translators:300:21)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:337:14)
    at async link (node:internal/modules/esm/module_job:70:21)
```

**Comment by goloroden** [comment]
Yes, this is because the `tsconfig.json` created by `tsc` with the `--init` flag is invalid JSON: comments are not allowed in there.

`tsc` internally ignores it (by apparently using a different JSON parser), but since `roboter` loads this file using the "normal" mechanisms, it fails.

So, unfortunately the only solution here is to remove the comments, to make `tsconfig.json` valid JSON.
